const mySpotifyCst = {
    MAIN_UI_LOGIN: "MAIN_UI_LOGIN",
    MAIN_UI_LOGOUT: "MAIN_UI_LOGOUT",
    MAIN_UI_LOGIN_SUCCESS: "MAIN_UI_LOGIN_SUCCESS",

    MAIN_UI_ADD: "MAIN_UI_ADD",
    MAIN_UI_DISPLAY: "MAIN_UI_DISPLAY",

    UI_ADD_NEW_PLAYLIST: "UI_ADD_NEW_PLAYLIST",
    UI_ADD_SELECTED_SONGS: "UI_ADD_SELECTED_SONGS",
    UI_ADD_SONGS: "UI_ADD_SONGS",    

    UI_SAVE_ALL: "UI_SAVE_ALL",

    UI_SELECT_A_PLAYLIST: "UI_SELECT_A_PLAYLIST",
    UI_DISPLAY_BY_ALBUM_ID: "UI_DISPLAY_BY_ALBUM_ID",
    UI_DISPLAY_BY_ALBUM_TYPE: "UI_DISPLAY_BY_ALBUM_TYPE",
    UI_DISPLAY_BY_ALBUM_NAME: "UI_DISPLAY_BY_ALBUM_NAME",

    UI_DISPLAY_BY_ARTIST_ID: "UI_DISPLAY_BY_ARTIST_ID",
    UI_DISPLAY_BY_ARTIST_NAME: "UI_DISPLAY_BY_ARTIST_NAME",
    UI_DISPLAY_BY_ARTIST_TYPE: "UI_DISPLAY_BY_ARTIST_TYPE",

    UI_DISPLAY_BY_SONG_BY_NAME: "UI_DISPLAY_BY_SONG_BY_NAME"
}

export default mySpotifyCst